### PR TITLE
[core] Consistent order of saved repeater items

### PR DESCRIPTION
**Pull request by nilslice**
Fix for #38

ping @bketelsen

### CODE REVIEW

**Comment by bketelsen** [comment]
You are my hero.  Many thanks for spending time fixing this!

**Comment by bketelsen** [comment]
Verified fix.  👍 💥 🎉

**Comment by nilslice** [comment]
Thank you for brining it to my attention - probably would have had to fix this in a hurry when I needed it at some point in the future.

**Comment by bketelsen** [comment]
somehow I always find the stuff :)

**Pull request merged**
