### PR TITLE
Fix UUID issues

### PR DESCRIPTION
**Pull request by nicksrandall**
The UUID package used just updated with some breaking changes that was causing ponzu to not be able to be installed. This fixes that.

### CODE REVIEW

**Comment by nilslice** [comment]
Hey @nicksrandall  -

Thanks for catching this! Minor detail, but could you ensure the formatting is correct with `gofmt` or manually indenting? 

see here: https://github.com/ponzu-cms/ponzu/pull/216/commits/91e61498c7db6b1abefdc2c23fdf132e823b6963#diff-f8ca100ba23285688010e5ea6c79f27eR32

Also, Ponzu currently vendors all dependencies. Would you update the `cmd/vendor/github.com/satori/go.uuid` directory with the current master? In order to bypass submodules, please remove the `.git` directory before you stage the change in Git.

Happy to help with this if needed!

**Comment by nilslice** [comment]
@nicksrandall - odd, my diff didn't show the formatting commit at first -- sorry about that! 

Would still be great to update the go.uuid package vendored if you don't mind.

**Comment by nilslice** [comment]
For reference, the PR mentioned is https://github.com/satori/go.uuid/issues/66

**Comment by nicksrandall** [comment]
I'm happy to make the change but I don't see the vendored files anywhere. I'm looking for `cmd/vendor/github.com/satori/go.uuid`. Could you point me to where that file lives?

**Comment by nilslice** [comment]
Sure thing, the files are here: https://github.com/ponzu-cms/ponzu/tree/master/cmd/ponzu/vendor/github.com/satori/go.uuid

you should see them in your own fork as well at the same path. Is that not the case?

basically just remove it, then copy the latest version of satori/go.uuid into the vendor directory. just make sure you remove the hidden `.git` directory before staging the change so we don't need to init submodules. sorry if this is redundant info!

**Comment by nilslice** [comment]
Sorry - I had written the path incorrectly in my original comment. Updated!

**Comment by nicksrandall** [comment]
Ok. I think I'm done. Thanks for your help!

**Comment by nilslice** [comment]
Thank you!

**Comment by nilslice** [comment]
@nicksrandall - was this the error you were seeing?
```
# github.com/ponzu-cms/ponzu/system/db
system/db/content.go:206:12: cannot assign 1 values to 2 variables
system/db/upload.go:33:12: cannot assign 1 values to 2 variables
```

**Comment by nilslice** [comment]
If not, we'll need to update the `system/db` package too, where the UUID is created. If you'd like to handle this as well, please go ahead! Otherwise, I'm happy to make the fix. I'll probably have to open an issue though, and fix/close later.

**Comment by nilslice** [comment]
You can see the build error here: https://circleci.com/gh/ponzu-cms/ponzu/36

**Comment by nicksrandall** [comment]
Yes, that was the error I was seeing.

**Pull request merged**
