### PR TITLE
make a proper item for Hookable methods

### PR DESCRIPTION
**Pull request by ivanov**
We have all of the information, it's nice to be access the item's members in a natural way, without having to look at the request.

This was already done for the approveContentHandler, but here I added to the editHandler of admin, and the createHandler of the API.

### CODE REVIEW

**Comment by ivanov** [comment]
It's possible (and desireable) to also make this work for the delete handlers via a DB lookup. I can make another PR for that or add it onto this one if you're amenable to that.

**Comment by nilslice** [comment]
@ivanov - can you elaborate a bit on how you're using the decoded `post` (or item, more generally)? I should have left myself some comments explaining why the decoding was even necessary to begin with, but now that I look back on the code it seems that the data is decoded from the post form, but never used.. now I don't remember why I did that hah!

**Comment by ivanov** [comment]
To be more concrete, with this PR, the members of a content type instance get populated, so the hooks can use them directly (as opposed to getting a zero-valued version of a content type).

Taking [this example](https://docs.ponzu-cms.org/Content/An-Overview/), we can add a `BeforeSave` hook that checks  `p.Title` directly without having to muck around and look into `req.PostForm`.

```
func (p *Post) BeforeSave(http.ResponseWriter, *http.Request) error {
	if p.Title == strings.ToUpper(p.Title) {
		return NoShoutingInTitlesError{}
	}
	return nil
}
```

Does that make sense?

**Comment by nilslice** [comment]
@ivanov - brilliant, yes, thank you. Sorry.. I knew there was a reason for it, and thinking back I suppose the other handlers did not have that done because they had no relevant hooks.. I have added lots of hooks as the project has evolved and populating the instance type must have slipped my mind. Please do add this in other areas if you don't mind.

Thanks for catching this!

**Comment by nilslice** [comment]
LOL'd at the return error in your example btw... :rofl:

**Comment by ivanov** [comment]
Ok, so delete hooks will also get the full item (when possible). Not sure if it's worth doing the same for the FileUpload stuff, what do you think?

**Comment by nilslice** [comment]
Thank you! I think the FileUpload parts can wait until hooks for them have been made. It would be cool to do a concurrent photo resizing utility which could be re-implemented to allow users to set/add sizes or other image processing to their FileUploads this way. Instead of adding these interface methods to `item.Hookable`, it would probably make sense to add an `item.Uploadable` or something to keep the FileUpload "hooks". 

Anyway, I'll merge these in now and if you have any ideas on what could be added to FileUpload or any other item.Hookable, I'd love to hear.

**Comment by ivanov** [comment]
Sweet. And thank *you* for making ponzu, @nilslice! It's fun to play with it.  🍰

**Comment by nilslice** [comment]
Glad you're enjoying it! Please keep playing with it.. I really appreciate the feedback and contributions.

**Pull request merged**
