### PR TITLE
[WIP] use spf13/cobra to process commands

### PR DESCRIPTION
**Pull request by martint17r**
This PR moves command line processing to [Cobra](//github.com/spf13/cobra). All commands are converted.
The calling syntax regarding flags changed subtly, mostly because flags are now added after the command, i.e. ```ponzu run --devhttps```.

### CODE REVIEW

**Comment by nilslice** [comment]
@martint17r - thank you for putting this up early! It would be great to get feedback from others on the general direction. I changed the base branch to `ponzu-dev`, which is what we develop against, so just keep that in mind for future commits.

**Comment by martint17r** [comment]
@Sirikon: pull the PR, then run 
```bash
cd $GOPATH/src/github.com/ponzu-cms/ponzu
go install ./cmd/ponzu
# change to a ponzu project
ponzu upgrade
ponzu build
```
I do not work with windows so the commands may be wrong.

To check whether you have successfully built the new version, run ponzu --help - the output has changed a bit, you should be able to notice the difference.

**Comment by Sirikon** [comment]
@martint17r Thanks!

Didn't have any existing Ponzu project in my machine, so, created a new one instead, and seems like everything worked well... :)

**Comment by nilslice** [comment]
@martint17r - this is great, thank you. the project really needed better organization and this is a big step forward.

can the command flags for each sub command be added to the main usage though? right now, running `$ ponzu` or `$ ponzu help` displays only the `--gocmd`, `--help, h`. iy would be good to show those with some context of which they are used.

**Comment by martint17r** [comment]
@nilslice IIRC the help command is a Cobra.Command, with a default implementation and can be overridden. I will check later today.

Right now, the help command only shows global flags - gocmd is used in a lot of commands, so I put it there. If you want to list them all, then this would need to be aggregated in some form. I will check that as well.

**Comment by martint17r** [comment]
I checked the cobra source: it is possible, will send another commit before monday morning.

**Comment by martint17r** [comment]
I think this is mergeable now.

**Comment by nilslice** [comment]
@martint17r - is it possible to avoid using spf13/viper...? it has a very large dependency graph

**Comment by nilslice** [comment]
ah, bad timing.. sorry to follow your merge suggestion with another ask.. 

I am working on some usage edits within your PR at the moment. So I do intend to merge this, but the viper dependency just struck me as a fairly excessive one if it is not absolutely required.

**Comment by nilslice** [comment]
> you added --https. Was that intentional?

Yea, I think if we did all the work to make TLS easy, we should promote that in the init script. Unless I'm not thinking straight and it has some bad side effect (other than if the system isn't configured properly or behind a public domain)

> that's a typo - it needs to be https-port
 
woops! fixed. thanks

**Comment by nilslice** [comment]
@martint17r - after our testing, this looks like it's ready to go. I'm going to merge it in now, and we can add the minor --dev/--branch flag updates later since they are mostly development based. Thank you again for all your work on this!

**Pull request merged**
