### PR TITLE
Just a little cleaner code

### PR DESCRIPTION
**Pull request by crackcomm**
I did it during reading the code.

### CODE REVIEW

**Comment by nilslice** [comment]
@crackcomm - hi, thank you for sending! Will look through this asap.

**Comment by nilslice** [comment]
This is all great - thx. sorry I didn't have it online, but would you re-push this to the `ponzu-dev` branch? I have made a commit or too since the last version available too, which are in the new branch.

**Comment by crackcomm** [comment]
I've read contributing section but forgot about that, I changed it.

**Comment by nilslice** [comment]
Thank you! I wasn't aware that I could edit the base branch for this commit. learn something new every day.. 

Once I run through some tests I will merge - I think I generally want to keep with the '&' syntax rather than 'new' -- unless you suggest a particular reason for 'new'? see: https://github.com/ponzu-cms/ponzu/pull/35/files#diff-6fdb1e817a428df8132da1d23cb983ceR146 I will go through and make those updates though. I contradict myself in the addon and content generator template code - but I think it makes it more obvious that the function returns a new pointer..

**Comment by crackcomm** [comment]
I just find it a much cleaner way to create a new empty structure.

**Pull request merged**
